#!/bin/sh
while read line ; do
    if [[ $line = E* ]] ; then
        echo -e "\033[31m$line\033[31m"
    elif [[ $line = I* ]] ; then
        echo -e "\033[32m$line\033[32m"
    elif [[ $line = W* ]] ; then
        echo -e "\033[33m$line\033[33m"
    elif [[ $line = D* ]] ; then
        echo -e "\033[36m$line\033[36m"
    fi
done
